### ISSUE TITLE
You can also suggest RenderHJS' ShoeBox

### ISSUE THREAD

**Issue by neonwarge04** [kittykatattack/learningPixi#12]
I've been using this for awhile:
http://renderhjs.net/shoebox/

Its free. Literally, this is the most easiest, hassle-free tool I found for awhile. It has a support for Pixi.js too! All you need to do is to drag all the files then boom! Its done, no complications. Good for tutorials too, especially if you don't want to waste your time learning how to configure a spritesheet (in a tutorial teaching game programming) complicated stuff are hidden through settings but there is nothing much to change.

Worth mentioning though.

**Comment by LukaszGrela** [comment]
It was mentioned in the book, and it is mentioned in the readme here so this can be closed:)
