### ISSUE TITLE
keyboard input in iframe

### ISSUE THREAD

**Issue by rad-corps** [kittykatattack/learningPixi#13]
First of all, myself and the internet thank you for creating such a valuable resource on pixi.
I have been using your keyboard function object for my last couple of projects but I can not seem to get it to work inside an iframe (I am trying to embed my game on my wordpress portfolio page). Is there any workaround you know of to make this code work in an iframe? 

Kind Regards

**Comment by rad-corps** [comment]
For anyone else who experiences this issue. It was solved by using the following

var realWindow = window.parent || window;
//.....  
//.....
//Attach event listeners
  realWindow.addEventListener(
    "keydown", key.downHandler.bind(key), false
  );
  realWindow.addEventListener(
    "keyup", key.upHandler.bind(key), false
  );

Thanks again for an amazing tutorial

**Comment by kittykatattack** [comment]
Thank you for posting your solution!
