### ISSUE TITLE
Game Engine using pixi

### ISSUE THREAD

**Issue by qsrahman** [kittykatattack/learningPixi#2]
I have read your excellent book Foundation Game Design with HTML5 and JavaScript many times :). While reading the book I searched for your web site but could not find it :( now I found your github account and site. It will be nice if you code a simple game engine like GA around pixi. However thanks for the excellent book and helpful code with explanation on github.

**Comment by kittykatattack** [comment]
Thank you!!
Yes, I'm actually building a micro game engine based on Pixi.
It's based on the [GA API](https://github.com/kittykatattack/ga), but runs Pixi in the background, so all the extra features of Pixi will easy to access.
I'm developing this for a new book I'm writing called "Learn PixiJS" which will be out by about mid-2015, and will publish the micro-engine as open-source when its complete enough.

**Comment by qsrahman** [comment]
Good to here that you are building a Pixi based game engine with a book. I can't wait to see "Learn PixiJS" in print though :). Is there any chance of putting the engine code on github early? ... curiosity might kill me :(

**Comment by kittykatattack** [comment]
I'll definitely create a github repo when it's ready :)

It's really just a thin layer API layer on top of Pixi that smoothes out and simplifies sprite and scene creation, along with an asset loader (sounds, images, JSON data), custom sound module, and a bunch of useful utility functions for games.
The goal is *simplicity*. What are the fewest number of versatile basic tools you need to create any game you can imagine? That's the challenge! I find most game HTML5 game engines (Phaser, etc.) needlessly complex.

I still need to fine-tune the API, finalize the architecture, do some testing, and build some example games - but it's not that far from being ready (maybe a few months away?)
I'll keep you posted!

**Comment by pooya72** [comment]
at first i wanna tell you THANK YOU for this golden tut :+1: 
secondly i wanna ask you for isometric design support in you thin layer API 
third when you'd like to complete your awesome tut ?

**Comment by qsrahman** [comment]
Thanks will keep watching for the github repo. 
>The goal is simplicity. What are the fewest number of versatile basic tools you need to create any game you can imagine?

I thinks that is a valid question. :)
