### ISSUE TITLE
 frame does not fit inside the base Texture dimensions

### ISSUE THREAD

**Issue by WangPengJu** [kittykatattack/learningPixi#21]
10.Make a sprite from a tileset sub-image

There's a mistake.

In this code：var rectangle = new Rectangle(192, 128, 64, 64); 

Trigger error：
Texture Error: frame does not fit inside the base Texture dimensions

I checked.

**Comment by a19352226** [comment]
I'm Chinese. Forgive my poor english. I am learning. PIXI really very good.

**Comment by kittykatattack** [comment]
Thank you for reporting this :)

Could you please post the code in which you found this error?

**Comment by a19352226** [comment]
l post the code in mine issue.

**Comment by kittykatattack** [comment]
Which version of Pixi are you using?

**Comment by WangPengJu** [comment]
just clone Pixi.js

**Comment by LucianoGraziani** [comment]
This occurs when you're not using the image of the examples/images folder, and instead you click the image of the tutorial (and you get the examples/image/screenshots one).

- The clicked one: https://github.com/kittykatattack/learningPixi/blob/master/examples/images/screenshots/09.png.
- The big one: https://github.com/kittykatattack/learningPixi/blob/master/examples/images/tileset.png.

**Comment by kittykatattack** [comment]
@LucianoGraziani Thanks for explaining that 😄

**Comment by wbbhacker** [comment]
@lgraziani2712 Thanks for this;

**Comment by Corbusier** [comment]
thx!@lgraziani2712
