### ISSUE TITLE
Question about translation.

### ISSUE THREAD

**Issue by Wangbicong** [kittykatattack/learningPixi#23]
I'm a college student majoring in CS from China. I consider that your book is so great, so I want to ask if I could translate it from English to Chinese in my free time. It will be also free in my github, and  it will have a mark that it's translated from you.

**Comment by kittykatattack** [comment]
Thank you so much for you offer!! :smile: 
Yes, that would be amazing if you could translate this into Chinese!

**Comment by Wangbicong** [comment]
It's my pleasure! I have learned so much from your free guide!

**Comment by kittykatattack** [comment]
If you have any questions about some of the meanings of concepts, or want help with some of the explanations, please let me know and I will help however I can.

**Comment by Krispomoho** [comment]
Hi, can you give me a link if you have translated this guide? thx.
