### ISSUE TITLE
how to play multiple frame sequence one after another in same movie clip ?

### ISSUE THREAD

**Issue by avinash511** [kittykatattack/learningPixi#24]
```
        animations: {
          selected: 'frame', // after frame complete changing selected to worm_move
            frame: [0, 37],
            worm_move: [38, 51]
        }
```

frame = animations[animations.selected];

At runtime i'm fetching currentFrame in ticker. And checking if currentFrame === frameEnd then performing gotoAndStop(37). Now problem is when 1st sequence is stopped I want to play another sequence in loop eg. worm_move. Both sequence belong to same movieclip. First sequence is working fine But we are facing issue in second sequence
/*\*  In ticker add both sequence are calling, when selected changed to second sequence(worm_move), it is not getting played **/ 
    this.ticker.add(() => {
         if (mc.currentFrame === frame[1]) {
             mc.gotoAndStop(frame[1]);
         }
    });

**Comment by kittykatattack** [comment]
Hi avinash511, You might want to consider asking your question here: 

http://www.html5gamedevs.com/forum/15-pixijs/
