### ISSUE TITLE
var texture = TextureCache["images/tileset.png"] Gives "TextureCache" is not defined Error

### ISSUE THREAD

**Issue by BarsikTheCaT** [kittykatattack/learningPixi#30]
I cannot even find TextureCache in the documentation, only found it being mentioned in some old thread as a part of PIXI.utils

**Comment by kaansoral** [comment]
Try `PIXI.TextureCache`

**Comment by BarsikTheCaT** [comment]
I mean, it's not in documentation - if I try to search it in http://pixijs.github.io/docs/ I get nothing. Any chance this thing got another name or does not exist anymore?
