### ISSUE TITLE
Specify Pixi.js Version used for the Tutorial

### ISSUE THREAD

**Issue by amorino** [kittykatattack/learningPixi#45]
Put at the beginning of Readme what version of Pixi.js is used. There's some changes here and there in Pixi.js and putting that will make the Guide consistent.

**Comment by MiroslavJelaska** [comment]
Hi @amorino,
the version is mentioned at the second sentence in the very beginning of the document, i.e. "Updated for Pixi v4.0". Do you think it's not that visible and can you suggest a fix?

What comes to my mind that it might be convenient to put a link to the release of the version of Pixi.js that is used in the guide, i.e. https://github.com/pixijs/pixi.js/releases/tag/v4.0.0

**Comment by amorino** [comment]
No, it was really my bad.

For some reason I wanted to find that information on the Setting Up section and I wasn't sure if the current version of Pixi was used.

**Comment by MiroslavJelaska** [comment]
@amorino That sound like a good idea. 👍 
I will suggest some changes and open a Pull request.

**Comment by MiroslavJelaska** [comment]
Here is Pull request #47

**Comment by aaronang** [comment]
I guess we can close this issue since #47 has been merged?
