### ISSUE TITLE
Update for Pixi v3.0!

### ISSUE THREAD

**Issue by kittykatattack** [kittykatattack/learningPixi#6]

**Comment by pass1234** [comment]
I searched and searched for a good walk through on how to use Pixi.js (first time user here) then I came across your walk-through and you saved me a lot of headaches. Any plans to update the rest of it, I hit the wall today when I read your disclaimer about the rest of the guide not being updated yet. 

Do i need to buy you a beer for motivation? :)

**Comment by kittykatattack** [comment]
Thanks!
I'm just extremely busy so add things piecemeal whenever I have a few spare moments.. should be new stuff on the way soon :)

**Comment by pooya72** [comment]
Hi pass1234 your right this How to is very helpful but if you are like me and want to use Pixi.js as a game development framework try Phaser too (Phaser uses Pixi as renderer), i was hesitant at first but Phaser is much easier and better for Online Game developing.

**Comment by kittykatattack** [comment]
Updated!
