### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by Nek-** [kittykatattack/learningPixi#71]
Hello,

I'd like to know if the license of this tutorial is free. Is it allowed to translate it? (without forget to refer to the original of course)

**Comment by kittykatattack** [comment]
Yes, it's completely free to use however you want.

**Comment by Nek-** [comment]
Hey, great news! Can you put a `LICENSE.md` file referencing the kind of license you agree with please?

https://creativecommons.org/choose/?lang=en

**Comment by kittykatattack** [comment]
Added

kk.

**Comment by Nek-** [comment]
Where ???!!!
