### ISSUE TITLE
You don't need to "install" pixi to use it

### ISSUE THREAD

**Issue by Vlek** [kittykatattack/learningPixi#72]
Simply adding the pixi script file's source to a script tag in an html file as suggested in your tutorial and opening the file in whatever browser that the person uses is fine. There's no need to create a webserver for one to do pixi.js scripting.

**Comment by kittykatattack** [comment]
Thanks Vlek!
However, I'm getting these sorts of errors without a web server:

![f_ 2017-12-07 at 10 42 07 am](https://user-images.githubusercontent.com/2936104/33723794-9a953932-db3b-11e7-9788-995d2ac63384.png)

errors without a web server:

**Comment by Vlek** [comment]
Sorry, I think it only worked for me because I was opening it through WebStorm. That might have been acting like a webserver.

**Comment by RexSkz** [comment]
Actually you need a web server to perform `ajax` or `fetch`, which PIXI uses to load a `json` resource.

A special situation is when you're in `Electron` or other similar environment (not a browser environment), just `file` protocol is fine.
