### ISSUE TITLE
Game Scenes

### ISSUE THREAD

**Issue by omarojo** [kittykatattack/learningPixi#9]
The section where you talk about the state and how is linked to a play() function. Was of no use to me. I couldnt understand how is that useful for Scene switching. I see Phaser.io has a very good state system, and is very easy to switch from scene to scene. But in PIXI I have no idea how people are modularizing their games and working with models and separate files. Otherwise.. the game is all dumped into just 1 single file and is all spaguetti messy. Im going crazy looking for a good suggestion but I just cant fine sample code that bests illustrates a good simple Game Scene management in PIXI

**Comment by kittykatattack** [comment]
Hi!

The "scenes" in this tutorial are just Pixi containers which contains sprites you want to display for a particular section of your game. So you might have a `titleScene` that contains things like the game's start button and title graphic. And you might have a `gameScene` which contains all your game sprites, like characters, backgrounds, and the score display. If you want your `titleScene` to disappear and display your `gameScene`, you could write some code like this:
```
titleScene.visible = false;
gameScene.visible = true;
```
That will make the title scene disappear and the game scene appear.

States are something different. A state is just a function that is called continuously in the game loop. Those functions contain specialized game code for a particular section of your game. For example, you might have two functions for two levels of your game:
```
function firstLevel() {
  //All the level one code...
}

function secondLevel() {
  //All the level two code...
}
```
If you want your game to switch to one of these states just change the global `state` variable to point to a function that contains the code you want to run:
```
state = firstLevel;
```
If the player finishes that level, you can then run all the code for the next level by pointing the `state` variable to the function that contains all that next level code, like this:
```
state = secondLevel;
```
`firstLevel` and `secondLevel` are just ordinary JavaScript functions. If they contain a lot of code, just save them as separate JS files and load them into your main program the same way you would load in any other external code (with a `<script>` tag, for example). You can have hundreds of separate JS files, each for a different state of you game, if you need them, and neatly organize the file structure however you like. There's no need for spaghetti code :smile:

**Comment by omarojo** [comment]
oohh... Im starting to understand. Reading one of your game sample projects.

**Comment by kittykatattack** [comment]
Please feel free to ask any questions :smile:
