### ISSUE TITLE
plase add the chinese learningPixi

### ISSUE THREAD

**Issue by Zainking** [kittykatattack/learningPixi#90]
Hello，I am Zain，from china.
I translate the learningPixi to chinese 1/10 in there：
[learningPixi中文版](https://github.com/Zainking/learningPixi)
I will finish it in next mouth；
I hope to add this version to your tutorial.
Wish more people enjoy Pixi.js！！！~

**Comment by kittykatattack** [comment]
That's brilliant, thank you so much for doing this!!!

**Comment by Zainking** [comment]
I finish it.

**Comment by kittykatattack** [comment]
Thank you! I've linked this to the main tutorial 😄
