### ISSUE TITLE
Issue with Delta Time in Section 21: Moving Sprites

### ISSUE THREAD

**Issue by honmanyau** [kittykatattack/learningPixi#93]
Hello there! Thank you very much for the fantastic tutorial! :)

I think there is potentially an issue with the following line(s) of code in the [Moving Sprites](https://github.com/kittykatattack/learningPixi#movingsprites) section of the tutorial concerning the use of delta time:

```javascript
cat.x += 1 + delta;
```

If I'm not mistaken, `delta` is not "the amount of fractional lag between frame", it is the fractional variation from the ideal time (1000 ms / 60) since the the last frame, that is:

```javascript
app.ticker.add((delta) => {
  console.log(1000 / 60 * delta === app.ticker.elapsedMS) // returns true most of the time (not all the time presumably because of floating point rounding errors)
});
```

As such, on a machine that is rendering at approximately 60 FPS, the cat would be moving at approximately 2 pixels per frame, instead of the 1 pixel per frame suggested in the tutorial with the current code.

Since delta is effectively the number of ideal frames (at a rate of 60 FPS) passed since the last frame, and we want to achieve 1 pixel per ideal frame, I think the correct code should be:

```javascript
app.ticker.add((delta) => {
  cat.x += delta;
});
```

As an aside, the `gameLoop()` function is currently declared outside of the scope of the `setup()` function and does not have access to the cat variable:

```javascript
function setup() {

  //Start the game loop by adding the `gameLoop` function to
  //Pixi's `ticker` and providing it with a `delta` argument.
  app.ticker.add(delta => gameLoop(delta));
}

function gameLoop(delta){

  //Move the cat 1 pixel 
  cat.x += 1;
}
```

If it's not intentional and if I'm not mistaken, the `gameLoop()` function should either be declared inside the `setup()` function or that the `cat` variable should be passed in.

I'm relatively new to this so many apologies in advance if it's a false alarm! I'm more than happy to create a PR and edit the related parts, too!

I hope that helps! Happy coding! :)

**Comment by mjomble** [comment]
I also just noticed the same.

As I understand, `cat.x += delta` would result in a constant movement speed of 60 pixels per second, whether the framerate is 60 FPS, 30 FPS or 10 FPS.

Whereas `cat.x += 1 + delta` would result in a speed of FPS + 60 pixels per second. So 120 pps at 60 FPS, 90 pps at 30 FPS, etc.

PS. Although adding a constant number to the delta would break framerate independence, multiplying it with a constant is ok and often encouraged.
For example, if `cat.x += delta` is too slow, you can try `cat.x += delta * 2`.
Or `cat.x += delta * 0.5` if it's too fast.

**Comment by mjomble** [comment]
> As an aside, the `gameLoop()` function is currently declared outside of the scope of the `setup()` function and does not have access to the cat variable

This seems to be addressed in the tutorial:

> (Notice that the `cat` variable needs to be defined outside the `setup` and `gameLoop` functions so that you can access it inside both of them.)

So that part of the tutorial looks correct to me :)

**Comment by honmanyau** [comment]
> (Notice that the cat variable needs to be defined outside the setup and gameLoop functions so that you can access it inside both of them.)

@mjomble, you are absolutely correct—I have overlooked that part of the code and jumped to the conclusion! :)
