### ISSUE TITLE
Failed to create Sprite by following tutorial

### ISSUE THREAD

**Issue by birdkingz** [kittykatattack/learningPixi#97]
Hi, I'm new to Pixi and I've been following the tutorial until "Creating Sprite". I followed the codes but my browser wasn't showing any images.

I don't know why it's not working.

```
<html>
    <style>* {padding: 0; margin: 0}</style>
<head>
  <meta charset="utf-8">
  <title>Test PIXI</title>
</head>
  <script src="pixi/pixi.min.js"></script>
<body>
  <script type="text/javascript">
    //Create a Pixi Application
      let app = new PIXI.Application();

      //Add the canvas that Pixi automatically created for you to the HTML document
      document.body.appendChild(app.view);

      PIXI.loader.add("images/alien_a.png").load(setup);
      
function setup()
{
    let cat = new PIXI.Sprite(PIXI.loader.resources["images/alien_a.png"].texture);
    
    app.stage.addChild(cat);
}
  </script>
</body>
</html>
```

I've an image file located in folder "images" and I have a "pixi" folder storing pixi.min.js file

From the Browser's console there's an error message
_Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded._

**Comment by jbockmon** [comment]
The code works for me. You are having a browser issue. I assume you are using chrome? Try firefox instead. Chrome has started tripping cross origin alerts when loading local files.

**Comment by birdkingz** [comment]
You are right. I tested it on Firefox and it works!
Thanks.
